"""Revision before test

Revision ID: 0d732f988e21
Revises: b595e220809e
Create Date: 2022-08-02 19:33:02.446914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d732f988e21'
down_revision = 'b595e220809e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
