"""Revision before test

Revision ID: e184457c520e
Revises: 0eac8a082f9c
Create Date: 2022-08-02 19:45:19.742111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e184457c520e'
down_revision = '0eac8a082f9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
