"""Revision before test

Revision ID: e3e7b236332b
Revises: 550b18ef9d7f
Create Date: 2022-08-02 20:41:15.475405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e7b236332b'
down_revision = '550b18ef9d7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
