"""Revision before test

Revision ID: 0373c9fedf60
Revises: e184457c520e
Create Date: 2022-08-02 20:11:02.557596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0373c9fedf60'
down_revision = 'e184457c520e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
