"""Revision before test

Revision ID: 550b18ef9d7f
Revises: 0373c9fedf60
Create Date: 2022-08-02 20:36:24.559733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550b18ef9d7f'
down_revision = '0373c9fedf60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
