"""The hottest new db changes around

Revision ID: b595e220809e
Revises: b4f71ea39d58
Create Date: 2022-08-02 03:26:05.932431

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b595e220809e'
down_revision = 'b4f71ea39d58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('height', sa.Numeric(), nullable=True))
    op.drop_column('user', 'wealth')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('wealth', sa.NUMERIC(), autoincrement=False, nullable=True))
    op.drop_column('user', 'height')
    # ### end Alembic commands ###
